[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "reflex>=0.7.13",
    "requests>=2.32.3",
    "yfinance>=0.2.54",
]
