[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.0",
    "plotly>=6.1.2",
    "reflex>=0.7.14",
    "requests>=2.32.4",
    "yfinance>=0.2.62",
]
